//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMTPracticalTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mmtdatabaseEntities1 : DbContext
    {
        public mmtdatabaseEntities1()
            : base("name=mmtdatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mmt_table> mmt_table { get; set; }
        public virtual DbSet<city_table> city_table { get; set; }
        public virtual DbSet<state_table> state_table { get; set; }
    }
}
